import { CPUModel } from './models/cpu';

export const defaultCPUs: CPUModel[] = [
  {
    name: 'Apple A17 Pro',
    brand: 'Apple',
    releaseYear: 2023,
    maxTemperatureC: 105,
    throttleTemperatureC: 95,
    clusters: [
      {
        name: 'Performance',
        cores: 2,
        threadsPerCore: 1,
        baseFrequencyGHz: 3.5,
        maxFrequencyGHz: 3.7,
        l1CacheKB: 192,
        l2CacheKB: 12800,
        avx: false,
        efficiency: false,
      },
      {
        name: 'Efficiency',
        cores: 4,
        threadsPerCore: 1,
        baseFrequencyGHz: 2.0,
        maxFrequencyGHz: 2.2,
        l1CacheKB: 128,
        l2CacheKB: 4000,
        avx: false,
        efficiency: true,
      },
    ],
  },
  {
    name: 'Apple M4 (iPad Pro 2024)',
    brand: 'Apple',
    releaseYear: 2024,
    maxTemperatureC: 105,
    throttleTemperatureC: 95,
    clusters: [
      {
        name: 'Performance',
        cores: 4,
        threadsPerCore: 1,
        baseFrequencyGHz: 3.8,
        maxFrequencyGHz: 4.0,
        l1CacheKB: 192,
        l2CacheKB: 12288,
        avx: false,
        efficiency: false,
      },
      {
        name: 'Efficiency',
        cores: 6,
        threadsPerCore: 1,
        baseFrequencyGHz: 2.2,
        maxFrequencyGHz: 2.4,
        l1CacheKB: 128,
        l2CacheKB: 4096,
        avx: false,
        efficiency: true,
      },
    ],
  },
  {
    name: 'Apple M4 (MacBook Air 2024)',
    brand: 'Apple',
    releaseYear: 2024,
    maxTemperatureC: 105,
    throttleTemperatureC: 95,
    clusters: [
      {
        name: 'Performance',
        cores: 4,
        threadsPerCore: 1,
        baseFrequencyGHz: 3.8,
        maxFrequencyGHz: 4.2,
        l1CacheKB: 192,
        l2CacheKB: 12288,
        avx: false,
        efficiency: false,
      },
      {
        name: 'Efficiency',
        cores: 6,
        threadsPerCore: 1,
        baseFrequencyGHz: 2.4,
        maxFrequencyGHz: 2.6,
        l1CacheKB: 128,
        l2CacheKB: 4096,
        avx: false,
        efficiency: true,
      },
    ],
  },
  {
    name: 'AMD Ryzen 9 5950X',
    brand: 'AMD',
    releaseYear: 2020,
    maxTemperatureC: 95,
    throttleTemperatureC: 90,
    clusters: [
      {
        name: 'CCD0',
        cores: 8,
        threadsPerCore: 2,
        baseFrequencyGHz: 3.4,
        maxFrequencyGHz: 4.9,
        l1CacheKB: 64,
        l2CacheKB: 512,
        l3CacheKB: 32000,
        avx: true,
      },
      {
        name: 'CCD1',
        cores: 8,
        threadsPerCore: 2,
        baseFrequencyGHz: 3.4,
        maxFrequencyGHz: 4.9,
        l1CacheKB: 64,
        l2CacheKB: 512,
        l3CacheKB: 32000,
        avx: true,
      },
    ],
  },
];
